name: RK U-Boot Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Initialize and update submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive

    - name: Clone rkbin
      run: |
        cd ..
        git clone --depth 1 https://github.com/rockchip-linux/rkbin.git

    - name: Install Python2 and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python2 \
          swig \
          make \
          gcc \
          device-tree-compiler \
          bison \
          flex \
          libssl-dev \
          libssl1.1 \
          xxd \
          wget \
          xz-utils \
          tree
        
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
        sudo update-alternatives --set python /usr/bin/python2

    - name: Download and setup toolchain
      run: |
        # 创建预构建目录结构
        cd ..
        ls
        pwd
        mkdir -p prebuilts/gcc/linux-x86/aarch64
        cd prebuilts/gcc/linux-x86/aarch64
        
        # 直接从 Linaro 下载工具链
        wget https://releases.linaro.org/components/toolchain/binaries/6.3-2017.05/aarch64-linux-gnu/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu.tar.xz
        tar xf gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu.tar.xz
        rm gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu.tar.xz
        
        # 返回到工作目录根
        cd ../../../..

    - name: Add toolchain to PATH
      run: |
        echo "$(pwd)/prebuilts/gcc/linux-x86/aarch64/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin" >> $GITHUB_PATH

    - name: Build U-Boot
      run: |
        
        
        # 设置工具链环境变量
        export CROSS_COMPILE=aarch64-linux-gnu-
        export ARCH=arm64
        # 执行编译
        ./make.sh rk3588
        ls
        

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: u-boot-images
        path: |
          uboot.img
          rk3588_spl_loader_v1.18.113.bin
        if-no-files-found: error
