name: RK U-Boot Build

on:
  push:
    branches: [ "next-dev" ]
  pull_request:
    branches: [ "next-dev" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code with Git (fix submodules)
      uses: actions/checkout@v4

    - name: Initialize and update submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive

    - name: Clone rkbin
      run: |
        cd ..
        git clone --depth 1 https://github.com/rockchip-linux/rkbin.git

    

    - name: Install Python2 and dependencies
      run: |
        sudo apt-get update
        # 安装Python2和必要组件
        sudo apt-get install -y \
          python2 \
          swig \
          make \
          gcc \
          gcc-aarch64-linux-gnu \
          device-tree-compiler \
          bison \
          flex \
          libssl-dev
        sudo apt-get install git gnupg flex bison gperf libsdl1.2-dev \
          libesd-java libwxgtk3.0-dev squashfs-tools build-essential zip curl \
          libncurses5-dev zlib1g-dev pngcrush schedtool libxml2 libxml2-utils \
          xsltproc lzop libc6-dev schedtool g++-multilib lib32z1-dev lib32ncurses5-dev \
          lib32readline-dev gcc-multilib libswitch-perl libssl-dev unzip zip device-tree-compiler \
          liblz4-tool python-pyelftools python3-pyelftools -y 
        
        # 设置Python2为默认版本
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
        sudo update-alternatives --set python /usr/bin/python2

    - name: Build U-Boot
      run: |
        ./make.sh rk3588

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: u-boot-images
        path: |
          uboot/*.img
